spring.application.name=deliverytracker
# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# = DATABASE CONFIG (POSTGRES)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/findit-local-db
spring.datasource.username=postgres
spring.datasource.password=password1234
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# = JPA / HIBERNATE
# ===============================
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# = JWT
# ===============================
jwt.secret=C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alzaimoorzainab@gmail.com
spring.mail.password=cpln zzdt byri ahhd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.debug=true
#
#
#

# ===============================
# = FILE UPLOAD
## ===============================
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB